package smb2

import (
	"context"
	"crypto/rand"
	"crypto/sha512"
	"fmt"
	"os"
	"sync"
	"sync/atomic"
	"time"

	"github.com/hirochachacha/go-smb2/internal/erref"
	"github.com/hirochachacha/go-smb2/internal/smb2"
)

// Negotiator contains options for func (*Dialer) Dial.
type Negotiator struct {
	RequireMessageSigning bool     // enforce signing?
	ClientGuid            [16]byte // if it's zero, generated by crypto/rand.
	SpecifiedDialect      uint16   // if it's zero, clientDialects is used. (See feature.go for more details)
}

func (n *Negotiator) makeRequest() (*smb2.NegotiateRequest, error) {
	req := new(smb2.NegotiateRequest)

	if n.RequireMessageSigning {
		req.SecurityMode = smb2.SMB2_NEGOTIATE_SIGNING_REQUIRED
	} else {
		req.SecurityMode = smb2.SMB2_NEGOTIATE_SIGNING_ENABLED
	}

	req.Capabilities = clientCapabilities

	if n.ClientGuid == zero {
		_, err := rand.Read(req.ClientGuid[:])
		if err != nil {
			return nil, &InternalError{err.Error()}
		}
	} else {
		req.ClientGuid = n.ClientGuid
	}

	if n.SpecifiedDialect != smb2.UnknownSMB {
		req.Dialects = []uint16{n.SpecifiedDialect}

		switch n.SpecifiedDialect {
		case smb2.SMB202:
		case smb2.SMB210:
		case smb2.SMB300:
		case smb2.SMB302:
		case smb2.SMB311:
			hc := &smb2.HashContext{
				HashAlgorithms: clientHashAlgorithms,
				HashSalt:       make([]byte, 32),
			}
			if _, err := rand.Read(hc.HashSalt); err != nil {
				return nil, &InternalError{err.Error()}
			}

			cc := &smb2.CipherContext{
				Ciphers: clientCiphers,
			}

			req.Contexts = append(req.Contexts, hc, cc)
		default:
			return nil, &InternalError{"unsupported dialect specified"}
		}
	} else {
		req.Dialects = clientDialects

		hc := &smb2.HashContext{
			HashAlgorithms: clientHashAlgorithms,
			HashSalt:       make([]byte, 32),
		}
		if _, err := rand.Read(hc.HashSalt); err != nil {
			return nil, &InternalError{err.Error()}
		}

		cc := &smb2.CipherContext{
			Ciphers: clientCiphers,
		}

		req.Contexts = append(req.Contexts, hc, cc)
	}

	return req, nil
}

func (n *Negotiator) negotiate(t transport, a *account, ctx context.Context) (*conn, error) {
	conn := &conn{
		t:                   t,
		outstandingRequests: newOutstandingRequests(),
		account:             a,
		rdone:               make(chan struct{}, 1),
	}

	go conn.runReciever()

retry:
	req, err := n.makeRequest()
	if err != nil {
		return nil, err
	}

	res, err := conn.sendRecv(ctx, req)
	if err != nil {
		return nil, err
	}
	defer res.close()

	r := smb2.NegotiateResponseDecoder(res.data(0))
	if r.IsInvalid() {
		return nil, &InvalidResponseError{"broken negotiate response format"}
	}

	if r.DialectRevision() == smb2.SMB2 {
		n.SpecifiedDialect = smb2.SMB210

		goto retry
	}

	if n.SpecifiedDialect != smb2.UnknownSMB && n.SpecifiedDialect != r.DialectRevision() {
		return nil, &InvalidResponseError{"unexpected dialect returned"}
	}

	conn.requireSigning = n.RequireMessageSigning || r.SecurityMode()&smb2.SMB2_NEGOTIATE_SIGNING_REQUIRED != 0
	conn.capabilities = clientCapabilities & r.Capabilities()
	conn.dialect = r.DialectRevision()
	conn.maxTransactSize = r.MaxTransactSize()
	conn.maxReadSize = r.MaxReadSize()
	conn.maxWriteSize = r.MaxWriteSize()

	// conn.gssNegotiateToken = r.SecurityBuffer()
	// conn.clientGuid = n.ClientGuid
	// copy(conn.serverGuid[:], r.ServerGuid())

	if conn.dialect != smb2.SMB311 {
		return conn, nil
	}

	// handle context for SMB311
	list := r.NegotiateContextList()
	for count := r.NegotiateContextCount(); count > 0; count-- {
		ctx := smb2.NegotiateContextDecoder(list)
		if ctx.IsInvalid() {
			return nil, &InvalidResponseError{"broken negotiate context format"}
		}

		switch ctx.ContextType() {
		case smb2.SMB2_PREAUTH_INTEGRITY_CAPABILITIES:
			d := smb2.HashContextDataDecoder(ctx.Data())
			if d.IsInvalid() {
				return nil, &InvalidResponseError{"broken hash context data format"}
			}

			algs := d.HashAlgorithms()

			if len(algs) != 1 {
				return nil, &InvalidResponseError{"multiple hash algorithms"}
			}

			conn.preauthIntegrityHashId = algs[0]

			switch conn.preauthIntegrityHashId {
			case smb2.SHA512:
				// Handshake requests are executed sequentially without concurrent access,
				// so conn.encodeBuf still holds the encoded request packet.
				updatePreauthHash(&conn.preauthIntegrityHashValue, conn.encodeBuf)
				updatePreauthHash(&conn.preauthIntegrityHashValue, res.get(0).bytes())
			default:
				return nil, &InvalidResponseError{"unknown hash algorithm"}
			}
		case smb2.SMB2_ENCRYPTION_CAPABILITIES:
			d := smb2.CipherContextDataDecoder(ctx.Data())
			if d.IsInvalid() {
				return nil, &InvalidResponseError{"broken cipher context data format"}
			}

			ciphs := d.Ciphers()

			if len(ciphs) != 1 {
				return nil, &InvalidResponseError{"multiple cipher algorithms"}
			}

			conn.cipherId = ciphs[0]

			switch conn.cipherId {
			case smb2.AES128CCM:
			case smb2.AES128GCM:
			default:
				return nil, &InvalidResponseError{"unknown cipher algorithm"}
			}
		default:
			// skip unsupported context
		}

		off := ctx.Next()

		if len(list) < off {
			list = nil
		} else {
			list = list[off:]
		}
	}

	return conn, nil
}

type outstandingRequest struct {
	msgId   uint64
	asyncId uint64
	cmd     uint16
	ctx     context.Context
	recv    chan *receivedPacket
	err     error
}

type outstandingRequests struct {
	m        sync.Mutex
	requests map[uint64]*outstandingRequest
}

func newOutstandingRequests() *outstandingRequests {
	return &outstandingRequests{
		requests: make(map[uint64]*outstandingRequest),
	}
}

func (r *outstandingRequests) pop(msgId uint64) (*outstandingRequest, bool) {
	r.m.Lock()
	defer r.m.Unlock()

	rr, ok := r.requests[msgId]
	if !ok {
		return nil, false
	}

	delete(r.requests, msgId)

	return rr, true
}

func (r *outstandingRequests) set(msgId uint64, rr *outstandingRequest) {
	r.m.Lock()
	defer r.m.Unlock()

	r.requests[msgId] = rr
}

func (r *outstandingRequests) shutdown(err error) {
	r.m.Lock()
	defer r.m.Unlock()

	for _, rr := range r.requests {
		rr.err = err
		close(rr.recv)
	}
}

type conn struct {
	t transport

	session                   *session
	outstandingRequests       *outstandingRequests
	sequenceWindow            uint64
	dialect                   uint16
	maxTransactSize           uint32
	maxReadSize               uint32
	maxWriteSize              uint32
	requireSigning            bool
	capabilities              uint32
	preauthIntegrityHashId    uint16
	preauthIntegrityHashValue [64]byte
	cipherId                  uint16

	account *account

	rdone chan struct{}

	m sync.Mutex

	err error

	// gssNegotiateToken []byte
	// serverGuid        [16]byte
	// clientGuid        [16]byte

	_useSession int32 // receiver use session?

	// reusable encode/encryption buffer. use it with sync.Mutex

	encodeBuf  []byte
	encryptBuf []byte
}

const minBufSize = 1024

func (conn *conn) allocEncodeBuf(size int) []byte {
	if cap(conn.encodeBuf) < size {
		newCap := size
		if newCap < minBufSize {
			newCap = minBufSize
		}
		conn.encodeBuf = make([]byte, newCap)
	} else {
		clear(conn.encodeBuf[:cap(conn.encodeBuf)])
	}
	return conn.encodeBuf[:size]
}

func (conn *conn) allocEncryptBuf(size int) []byte {
	if cap(conn.encryptBuf) < size {
		newCap := size
		if newCap < minBufSize {
			newCap = minBufSize
		}
		conn.encryptBuf = make([]byte, newCap)
	} else {
		clear(conn.encryptBuf[:cap(conn.encryptBuf)])
	}
	return conn.encryptBuf[:size]
}

var receivedPacketPool = sync.Pool{
	New: func() interface{} {
		return &receivedPacket{
			pkt: make([]byte, 0, 64*1024),
		}
	},
}

type receivedPacket struct {
	pkt []byte
}

func (rp *receivedPacket) bytes() []byte {
	if rp == nil {
		return nil
	}
	return rp.pkt
}

func (rp *receivedPacket) packetCodec() smb2.PacketCodec {
	if rp == nil {
		return nil
	}
	return smb2.PacketCodec(rp.pkt)
}

func (rp *receivedPacket) data() []byte {
	if rp == nil {
		return nil
	}
	return rp.packetCodec().Data()
}

func (rp *receivedPacket) transformCodec() smb2.TransformCodec {
	if rp == nil {
		return nil
	}
	return smb2.TransformCodec(rp.pkt)
}

func (rp *receivedPacket) splitNext() (head, tail *receivedPacket, err error) {
	p := rp.packetCodec()
	if p.IsInvalid() {
		return nil, nil, &InvalidResponseError{"invalid chained packet header"}
	}

	off := p.NextCommand()
	if off == 0 {
		return rp, nil, nil
	}

	if off < 64 || uint64(off) > uint64(len(rp.pkt)) {
		return nil, nil, &InvalidResponseError{"NextCommand offset out of bounds"}
	}

	head = allocReceivedPacket(int(off))
	copy(head.bytes(), rp.pkt[:off])

	tail = allocReceivedPacket(len(rp.pkt) - int(off))
	copy(tail.bytes(), rp.pkt[off:])

	rp.close()
	return head, tail, nil
}

func (rp *receivedPacket) close() {
	if rp == nil || rp.pkt == nil {
		return
	}
	b := rp.pkt
	if cap(b) > 1024*1024 {
		rp.pkt = nil
		return
	}
	clear(b[:cap(b)])
	rp.pkt = b[:0]
	receivedPacketPool.Put(rp)
}

func allocReceivedPacket(size int) *receivedPacket {
	rp := receivedPacketPool.Get().(*receivedPacket)
	if cap(rp.pkt) < size {
		rp.pkt = make([]byte, size)
	} else {
		rp.pkt = rp.pkt[:size]
	}
	return rp
}

func (conn *conn) allocReceivedPacket(size int) *receivedPacket {
	return allocReceivedPacket(size)
}

func updatePreauthHash(hashVal *[64]byte, pkt []byte) {
	h := sha512.New()
	h.Write(hashVal[:])
	h.Write(pkt)
	h.Sum(hashVal[:0])
}

func (conn *conn) useSession() bool {
	return atomic.LoadInt32(&conn._useSession) != 0
}

func (conn *conn) enableSession() {
	atomic.StoreInt32(&conn._useSession, 1)
}

func (conn *conn) newTimer() *time.Timer {
	return time.NewTimer(5 * time.Second)
}

func (conn *conn) sendRecv(ctx context.Context, reqs ...smb2.Packet) (*response, error) {
	rrs, err := conn.send(ctx, reqs...)
	if err != nil {
		return nil, err
	}

	rpkts := make([]*receivedPacket, len(rrs))
	for i, rr := range rrs {
		rp, err := conn.recv(rr)
		if err != nil {
			return nil, err
		}
		rpkts[i] = rp
	}

	return &response{rpkts: rpkts}, nil
}

/*
mustSign returns true if req needs to be signed.

MS-SMB2 3.2.4.1.1 describes when a message needs to be signed.
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/973630a8-8aa1-4398-89a8-13cf830f194d
*/
func (conn *conn) mustSign(sessionFlags uint16, req smb2.Packet) bool {
	// a 'guest' user or a session without a key can't sign requests
	if sessionFlags&(smb2.SMB2_SESSION_FLAG_IS_GUEST|smb2.SMB2_SESSION_FLAG_IS_NULL) != 0 {
		return false
	}

	// true if the library user requested it at initialization or if the server
	// requires it
	if conn.requireSigning {
		return true
	}

	// Only SMB 3.1.1 requires TREE_CONNECT to always be signed, but for
	// simplicity's sake, we'll sign it no matter the dialect version.
	_, isTreeConnect := req.(*smb2.TreeConnectRequest)
	return isTreeConnect
}

func (conn *conn) send(ctx context.Context, reqs ...smb2.Packet) (rrs []*outstandingRequest, err error) {
	msgIds, totalCreditCharge, err := conn.account.loan(ctx, reqs...)
	if err != nil {
		return nil, err
	}

	conn.m.Lock()
	defer conn.m.Unlock()

	if conn.err != nil {
		conn.account.unloan(totalCreditCharge)
		return nil, conn.err
	}

	select {
	case <-ctx.Done():
		conn.account.unloan(totalCreditCharge)
		return nil, &ContextError{Err: ctx.Err()}
	default:
		// do nothing
	}

	rrs, pkt, err := conn.makeOutstandingRequest(ctx, msgIds, reqs...)
	if err != nil {
		conn.account.unloan(totalCreditCharge)
		return nil, err
	}

	_, err = conn.t.Write(pkt)
	if err != nil {
		for _, rr := range rrs {
			conn.outstandingRequests.pop(rr.msgId)
		}
		conn.account.unloan(totalCreditCharge)
		return nil, &TransportError{err}
	}

	return rrs, nil
}

func (conn *conn) makeOutstandingRequest(ctx context.Context, msgIds []uint64, reqs ...smb2.Packet) (rrs []*outstandingRequest, pkt []byte, err error) {
	s := conn.session
	rrs = make([]*outstandingRequest, len(reqs))

	// Compound request (len(reqs) > 1)
	var totalSize int
	sizes := make([]int, len(reqs))
	for i, req := range reqs {
		sz := req.Size()
		if i < len(reqs)-1 {
			alignedSz := smb2.Roundup(sz, 8)
			req.SetNextCommand(uint32(alignedSz))
			sizes[i] = alignedSz
			totalSize += alignedSz
		} else {
			req.SetNextCommand(0)
			sizes[i] = sz
			totalSize += sz
		}
	}

	for i, req := range reqs {
		msgId := msgIds[i]

		if i > 0 {
			req.SetFlags(smb2.SMB2_FLAGS_RELATED_OPERATIONS)
		}

		rr := &outstandingRequest{
			cmd:   req.Command(),
			msgId: msgId,
			ctx:   ctx,
			recv:  make(chan *receivedPacket, 1),
		}

		rrs[i] = rr
	}

	pkt = conn.allocEncodeBuf(totalSize)

	off := 0
	for i, req := range reqs {
		req.Encode(pkt[off:])
		off += sizes[i]
	}

	if s != nil {
		tc := s.treeConnTables[smb2.PacketCodec(pkt).TreeId()]
		if s.sessionFlags&smb2.SMB2_SESSION_FLAG_ENCRYPT_DATA != 0 || (tc != nil && tc.shareFlags&smb2.SMB2_SHAREFLAG_ENCRYPT_DATA != 0) {
			encSize := 52 + len(pkt) + 16
			encryptBuf := conn.allocEncryptBuf(encSize)
			pkt, err = s.encrypt(pkt, encryptBuf)
			if err != nil {
				return nil, nil, &InternalError{err.Error()}
			}
		} else {
			off = 0
			requireSigning := false
			for _, req := range reqs {
				if conn.mustSign(s.sessionFlags, req) {
					requireSigning = true
					break
				}
			}
			for i := range reqs {
				subPkt := pkt[off : off+sizes[i]]
				if requireSigning {
					s.sign(subPkt)
				}
				off += sizes[i]
			}
		}
	}

	for _, rr := range rrs {
		conn.outstandingRequests.set(rr.msgId, rr)
	}

	return rrs, pkt, nil
}

func (conn *conn) recv(rr *outstandingRequest) (*receivedPacket, error) {
	select {
	case rp := <-rr.recv:
		if rr.err != nil {
			return nil, rr.err
		}
		rp, err := accept(rr.cmd, rp)
		if err != nil {
			return nil, err
		}
		return rp, nil
	case <-rr.ctx.Done():
		conn.outstandingRequests.pop(rr.msgId)

		return nil, &ContextError{Err: rr.ctx.Err()}
	}
}

func (conn *conn) runReciever() {
	var err error

	// A panic should shutdown the connection
	defer func() {
		if r := recover(); r != nil {
			err = &InvalidResponseError{fmt.Sprintf("receiver panic: %v", r)}
			conn.m.Lock()
			defer conn.m.Unlock()
			conn.outstandingRequests.shutdown(err)
			conn.err = err
		}
	}()

	for {
		n, e := conn.t.ReadSize()
		if e != nil {
			err = &TransportError{e}

			goto exit
		}

		rp := conn.allocReceivedPacket(n)

		_, e = conn.t.Read(rp.bytes())
		if e != nil {
			rp.close()
			err = &TransportError{e}

			goto exit
		}

		hasSession := conn.useSession()

		var isEncrypted bool

		if hasSession {
			var errDecrypt error
			rp, errDecrypt, isEncrypted = conn.tryDecrypt(rp)
			if errDecrypt != nil {
				rp.close()
				logger.Println("skip:", errDecrypt)

				continue
			}

			p := rp.packetCodec()
			if s := conn.session; s != nil {
				if s.sessionId != p.SessionId() {
					rp.close()
					logger.Println("skip:", &InvalidResponseError{"unknown session id"})

					continue
				}

				if tc, ok := s.treeConnTables[p.TreeId()]; ok {
					if tc.treeId != p.TreeId() {
						rp.close()
						logger.Println("skip:", &InvalidResponseError{"unknown tree id"})

						continue
					}
				}
			}
		}

		p := rp.packetCodec()

		// validate the packet if it doesn't have a session yet. tryDecrypt
		// already checks the packet validity when there is a session.
		if !hasSession && p.IsInvalid() {
			rp.close()
			logger.Println("skip:", &InvalidResponseError{"invalid packet header"})
			continue
		}

		for rp != nil {
			var singleRp, nextRp *receivedPacket
			singleRp, nextRp, err = rp.splitNext()
			if err != nil {
				rp.close()
				logger.Println("skip:", err)
				break
			}

			if hasSession {
				e = conn.tryVerify(singleRp.bytes(), isEncrypted)
			}

			if e := conn.tryHandle(singleRp, e); e != nil {
				logger.Println("skip:", e)
			}

			rp = nextRp
		}
	}

exit:
	select {
	case <-conn.rdone:
		err = nil
	default:
		logger.Println("error:", err)
	}

	conn.m.Lock()
	defer conn.m.Unlock()

	conn.outstandingRequests.shutdown(err)

	conn.err = err
}

func accept(cmd uint16, rp *receivedPacket) (res *receivedPacket, err error) {
	p := rp.packetCodec()
	if command := p.Command(); cmd != command {
		rp.close()
		return nil, &InvalidResponseError{fmt.Sprintf("expected command: %s, got %s", cmdToString(cmd), cmdToString(command))}
	}

	status := erref.NtStatus(p.Status())

	switch status {
	case erref.STATUS_SUCCESS:
		if !validateResponseData(cmd, p.Data()) {
			rp.close()
			return nil, &InvalidResponseError{fmt.Sprintf("broken %s response format", cmdToString(cmd))}
		}
		return rp, nil
	case erref.STATUS_OBJECT_NAME_COLLISION:
		rp.close()
		return nil, os.ErrExist
	case erref.STATUS_OBJECT_NAME_NOT_FOUND, erref.STATUS_OBJECT_PATH_NOT_FOUND:
		rp.close()
		return nil, os.ErrNotExist
	case erref.STATUS_ACCESS_DENIED, erref.STATUS_CANNOT_DELETE:
		rp.close()
		return nil, os.ErrPermission
	}

	switch cmd {
	case smb2.SMB2_SESSION_SETUP:
		if status == erref.STATUS_MORE_PROCESSING_REQUIRED {
			return rp, nil
		}
	case smb2.SMB2_QUERY_INFO:
		if status == erref.STATUS_BUFFER_OVERFLOW {
			rp.close()
			return nil, &ResponseError{Code: uint32(status)}
		}
	case smb2.SMB2_IOCTL:
		if status == erref.STATUS_BUFFER_OVERFLOW {
			if !smb2.IoctlResponseDecoder(p.Data()).IsInvalid() {
				return rp, &ResponseError{Code: uint32(status)}
			}
		}
	case smb2.SMB2_READ:
		if status == erref.STATUS_BUFFER_OVERFLOW {
			rp.close()
			return nil, &ResponseError{Code: uint32(status)}
		}
	case smb2.SMB2_CHANGE_NOTIFY:
		if status == erref.STATUS_NOTIFY_ENUM_DIR {
			rp.close()
			return nil, &ResponseError{Code: uint32(status)}
		}
	}

	err = acceptError(uint32(status), p.Data())
	rp.close()
	return nil, err
}

func acceptError(status uint32, res []byte) error {
	r := smb2.ErrorResponseDecoder(res)
	if r.IsInvalid() {
		return &InvalidResponseError{"broken error response format"}
	}

	eData := r.ErrorData()

	if count := r.ErrorContextCount(); count != 0 {
		data := make([][]byte, count)

		for i := range data {
			ctx := smb2.ErrorContextResponseDecoder(eData)
			if ctx.IsInvalid() {
				return &InvalidResponseError{"broken error context response format"}
			}

			data[i] = ctx.ErrorContextData()

			next := ctx.Next()

			if len(eData) < next {
				return &InvalidResponseError{"broken error context response format"}
			}

			eData = eData[next:]
		}
		return &ResponseError{Code: status, data: data}
	}
	return &ResponseError{Code: status, data: [][]byte{eData}}
}

func (conn *conn) tryDecrypt(rp *receivedPacket) (*receivedPacket, error, bool) {
	p := rp.packetCodec()
	if p.IsInvalid() {
		t := rp.transformCodec()
		if t.IsInvalid() {
			return rp, &InvalidResponseError{"broken packet header format"}, false
		}

		if t.Flags() != smb2.Encrypted {
			return rp, &InvalidResponseError{"encrypted flag is not on"}, false
		}

		if conn.session == nil || conn.session.sessionId != t.SessionId() {
			return rp, &InvalidResponseError{"unknown session id returned"}, false
		}

		pkt, err := conn.session.decrypt(rp.bytes())
		if err != nil {
			return rp, &InvalidResponseError{err.Error()}, false
		}

		rp.pkt = pkt
		return rp, nil, true
	}

	return rp, nil, false
}

func (conn *conn) tryVerify(pkt []byte, isEncrypted bool) error {
	p := smb2.PacketCodec(pkt)

	msgID := p.MessageId()

	// MS-SMB2 3.2.5.1.3 states that the client MUST skip signature processing if:
	// - MessageId is 0xFFFFFFFFFFFFFFFF
	// - Status in the SMB2 header is STATUS_PENDING
	// 		- 3.3.4.1.1 says servers should skip signing interim responses to async requests - STATUS_PENDING is an interim response
	// - Client is using the SMB 3.x dialect and the message was successfully decrypted+authenticated (isEncrypted=true)
	if msgID == 0xFFFFFFFFFFFFFFFF {
		return nil
	}
	if erref.NtStatus(p.Status()) == erref.STATUS_PENDING {
		return nil
	}
	if isEncrypted {
		return nil
	}

	s := conn.session
	if s == nil {
		return &InvalidResponseError{"packet received before session established"}
	}
	if s.sessionId != p.SessionId() {
		return &InvalidResponseError{"packet for unknown session"}
	}

	// guest and null sessions can't produce signatures, so they don't need to be verified
	if s.sessionFlags&(smb2.SMB2_SESSION_FLAG_IS_GUEST|smb2.SMB2_SESSION_FLAG_IS_NULL) != 0 {
		return nil
	}

	// verify if 1) the connection requires signing or 2) if the message itself is signed
	if conn.requireSigning || p.Flags()&smb2.SMB2_FLAGS_SIGNED != 0 {
		if !s.verify(pkt) {
			return &InvalidResponseError{"packet failed signature verification"}
		}
		return nil
	}

	// the message was not signed AND signing is not required
	return nil
}

func (conn *conn) tryHandle(rp *receivedPacket, e error) error {
	p := rp.packetCodec()

	msgId := p.MessageId()

	rr, ok := conn.outstandingRequests.pop(msgId)
	switch {
	case !ok:
		rp.close()
		return &InvalidResponseError{"unknown message id returned"}
	case e != nil:
		rp.close()
		rr.err = e

		close(rr.recv)
	case erref.NtStatus(p.Status()) == erref.STATUS_PENDING:
		rp.close()
		rr.asyncId = p.AsyncId()
		conn.account.charge(p.CreditResponse())
		conn.outstandingRequests.set(msgId, rr)
	default:
		conn.account.charge(p.CreditResponse())

		rr.recv <- rp
	}

	return nil
}

func validateResponseData(cmd uint16, data []byte) bool {
	switch cmd {
	case smb2.SMB2_NEGOTIATE:
		return !smb2.NegotiateResponseDecoder(data).IsInvalid()
	case smb2.SMB2_SESSION_SETUP:
		return !smb2.SessionSetupResponseDecoder(data).IsInvalid()
	case smb2.SMB2_LOGOFF:
		return !smb2.LogoffResponseDecoder(data).IsInvalid()
	case smb2.SMB2_TREE_CONNECT:
		return !smb2.TreeConnectResponseDecoder(data).IsInvalid()
	case smb2.SMB2_TREE_DISCONNECT:
		return !smb2.TreeDisconnectResponseDecoder(data).IsInvalid()
	case smb2.SMB2_CREATE:
		return !smb2.CreateResponseDecoder(data).IsInvalid()
	case smb2.SMB2_CLOSE:
		return !smb2.CloseResponseDecoder(data).IsInvalid()
	case smb2.SMB2_FLUSH:
		return !smb2.FlushResponseDecoder(data).IsInvalid()
	case smb2.SMB2_READ:
		return !smb2.ReadResponseDecoder(data).IsInvalid()
	case smb2.SMB2_WRITE:
		return !smb2.WriteResponseDecoder(data).IsInvalid()
	case smb2.SMB2_QUERY_DIRECTORY:
		return !smb2.QueryDirectoryResponseDecoder(data).IsInvalid()
	case smb2.SMB2_QUERY_INFO:
		return !smb2.QueryInfoResponseDecoder(data).IsInvalid()
	case smb2.SMB2_SET_INFO:
		return !smb2.SetInfoResponseDecoder(data).IsInvalid()
	case smb2.SMB2_IOCTL:
		return !smb2.IoctlResponseDecoder(data).IsInvalid()
	case smb2.SMB2_ECHO:
		return !smb2.EchoResponseDecoder(data).IsInvalid()
	default:
		panic("unreachable")
	}
}

func cmdToString(cmd uint16) string {
	switch cmd {
	case smb2.SMB2_NEGOTIATE:
		return "SMB2_NEGOTIATE"
	case smb2.SMB2_SESSION_SETUP:
		return "SMB2_SESSION_SETUP"
	case smb2.SMB2_LOGOFF:
		return "SMB2_LOGOFF"
	case smb2.SMB2_TREE_CONNECT:
		return "SMB2_TREE_CONNECT"
	case smb2.SMB2_TREE_DISCONNECT:
		return "SMB2_TREE_DISCONNECT"
	case smb2.SMB2_CREATE:
		return "SMB2_CREATE"
	case smb2.SMB2_CLOSE:
		return "SMB2_CLOSE"
	case smb2.SMB2_FLUSH:
		return "SMB2_FLUSH"
	case smb2.SMB2_READ:
		return "SMB2_READ"
	case smb2.SMB2_WRITE:
		return "SMB2_WRITE"
	case smb2.SMB2_LOCK:
		return "SMB2_LOCK"
	case smb2.SMB2_IOCTL:
		return "SMB2_IOCTL"
	case smb2.SMB2_CANCEL:
		return "SMB2_CANCEL"
	case smb2.SMB2_ECHO:
		return "SMB2_ECHO"
	case smb2.SMB2_QUERY_DIRECTORY:
		return "SMB2_QUERY_DIRECTORY"
	case smb2.SMB2_CHANGE_NOTIFY:
		return "SMB2_CHANGE_NOTIFY"
	case smb2.SMB2_QUERY_INFO:
		return "SMB2_QUERY_INFO"
	case smb2.SMB2_SET_INFO:
		return "SMB2_SET_INFO"
	case smb2.SMB2_OPLOCK_BREAK:
		return "SMB2_OPLOCK_BREAK"
	default:
		return fmt.Sprintf("0x%04x", cmd)
	}
}
