package smb2

import (
	"context"
	"crypto/rand"
	"crypto/sha512"
	"fmt"
	"net"
	"slices"
	"sync"
	"sync/atomic"
	"time"

	"github.com/hirochachacha/go-smb2/internal/erref"
	"github.com/hirochachacha/go-smb2/internal/smb2"
)

// Negotiator contains options for func (*Dialer) Dial.
type Negotiator struct {
	RequireMessageSigning bool     // enforce signing?
	ClientGuid            [16]byte // if it's zero, generated by crypto/rand.
	SpecifiedDialect      uint16   // if it's zero, clientDialects is used. (See feature.go for more details)
}

func (n *Negotiator) makeRequest() (*smb2.NegotiateRequest, error) {
	req := new(smb2.NegotiateRequest)

	if n.RequireMessageSigning {
		req.SecurityMode = smb2.SMB2_NEGOTIATE_SIGNING_REQUIRED
	} else {
		req.SecurityMode = smb2.SMB2_NEGOTIATE_SIGNING_ENABLED
	}

	req.Capabilities = clientCapabilities

	if n.ClientGuid == zero {
		_, err := rand.Read(req.ClientGuid[:])
		if err != nil {
			return nil, &InternalError{err.Error()}
		}
	} else {
		req.ClientGuid = n.ClientGuid
	}

	if n.SpecifiedDialect != smb2.UnknownSMB {
		req.Dialects = []uint16{n.SpecifiedDialect}

		switch n.SpecifiedDialect {
		case smb2.SMB202, smb2.SMB210:
			req.Capabilities = 0
		case smb2.SMB300, smb2.SMB302:
		case smb2.SMB311:
			hc, err := newHashContext()
			if err != nil {
				return nil, err
			}
			req.Contexts = append(req.Contexts, hc, newCipherContext())
		default:
			return nil, &InternalError{"unsupported dialect specified"}
		}
	} else {
		req.Dialects = clientDialects

		hc, err := newHashContext()
		if err != nil {
			return nil, err
		}
		req.Contexts = append(req.Contexts, hc, newCipherContext())
	}

	return req, nil
}

func newHashContext() (*smb2.HashContext, error) {
	hc := &smb2.HashContext{
		HashAlgorithms: clientHashAlgorithms,
		HashSalt:       make([]byte, 32),
	}
	if _, err := rand.Read(hc.HashSalt); err != nil {
		return nil, &InternalError{err.Error()}
	}
	return hc, nil
}

func newCipherContext() *smb2.CipherContext {
	return &smb2.CipherContext{
		Ciphers: clientCiphers,
	}
}

func (n *Negotiator) negotiate(ctx context.Context, t transport, a *account, writeTimeout time.Duration) (c *conn, err error) {
	conn := &conn{
		t:                   t,
		outstandingRequests: newOutstandingRequests(),
		account:             a,
		rdone:               make(chan struct{}, 1),
		writeTimeout:        writeTimeout,
	}

	defer func() {
		if err != nil {
			conn.close(err)
		}
	}()

	go conn.runReceiver()

	neg := *n

retry:
	req, err := neg.makeRequest()
	if err != nil {
		return nil, err
	}

	res, err := conn.sendRecv(ctx, req)
	if err != nil {
		return nil, err
	}
	defer res.close()

	r := smb2.NegotiateResponseDecoder(res.data(0))

	if r.DialectRevision() == smb2.SMB2 {
		// Retry at most once with a specified dialect; a second wildcard
		// response means the server is misbehaving.
		if neg.SpecifiedDialect != smb2.UnknownSMB {
			return nil, &InvalidResponseError{"unexpected dialect returned"}
		}
		neg.SpecifiedDialect = smb2.SMB210

		// Release the previous response buffer before retrying.
		res.close()

		goto retry
	}

	if neg.SpecifiedDialect != smb2.UnknownSMB {
		if neg.SpecifiedDialect != r.DialectRevision() {
			return nil, &InvalidResponseError{"unexpected dialect returned"}
		}
	} else if !slices.Contains(clientDialects, r.DialectRevision()) {
		return nil, &InvalidResponseError{"unexpected dialect returned"}
	}

	conn.requireSigning = neg.RequireMessageSigning || r.SecurityMode()&smb2.SMB2_NEGOTIATE_SIGNING_REQUIRED != 0
	conn.capabilities = clientCapabilities & r.Capabilities()
	conn.dialect = r.DialectRevision()
	conn.maxTransactSize = r.MaxTransactSize()
	conn.maxReadSize = r.MaxReadSize()
	conn.maxWriteSize = r.MaxWriteSize()

	// conn.gssNegotiateToken = r.SecurityBuffer()
	// conn.clientGuid = n.ClientGuid
	// copy(conn.serverGuid[:], r.ServerGuid())

	if conn.dialect != smb2.SMB311 {
		return conn, nil
	}

	// handle context for SMB311
	var seenPreauth, seenEncryption bool
	list := r.NegotiateContextList()
	for count := r.NegotiateContextCount(); count > 0; count-- {
		nc := smb2.NegotiateContextDecoder(list)
		if nc.IsInvalid() {
			return nil, &InvalidResponseError{"broken negotiate context format"}
		}

		switch nc.ContextType() {
		case smb2.SMB2_PREAUTH_INTEGRITY_CAPABILITIES:
			if seenPreauth {
				return nil, &InvalidResponseError{"duplicate preauth integrity capabilities context"}
			}
			seenPreauth = true

			d := smb2.HashContextDataDecoder(nc.Data())
			if d.IsInvalid() {
				return nil, &InvalidResponseError{"broken hash context data format"}
			}

			algs := d.HashAlgorithms()

			if len(algs) != 1 {
				return nil, &InvalidResponseError{"multiple hash algorithms"}
			}

			if !slices.Contains(clientHashAlgorithms, algs[0]) {
				return nil, &InvalidResponseError{"unsupported hash algorithm"}
			}

			conn.preauthIntegrityHashId = algs[0]

			// Handshake requests are executed sequentially without concurrent access,
			// so conn.encodeBuf still holds the encoded request packet.
			updatePreauthHash(&conn.preauthIntegrityHashValue, conn.encodeBuf)
			updatePreauthHash(&conn.preauthIntegrityHashValue, res.bytes(0))
		case smb2.SMB2_ENCRYPTION_CAPABILITIES:
			if seenEncryption {
				return nil, &InvalidResponseError{"duplicate encryption capabilities context"}
			}
			seenEncryption = true

			d := smb2.CipherContextDataDecoder(nc.Data())
			if d.IsInvalid() {
				return nil, &InvalidResponseError{"broken cipher context data format"}
			}

			ciphs := d.Ciphers()

			if len(ciphs) != 1 {
				return nil, &InvalidResponseError{"multiple cipher algorithms"}
			}

			if !slices.Contains(clientCiphers, ciphs[0]) {
				return nil, &InvalidResponseError{"unsupported cipher algorithm"}
			}

			conn.cipherId = ciphs[0]
		default:
			// skip unsupported context
		}

		off := nc.Next()

		if len(list) < off {
			list = nil
		} else {
			list = list[off:]
		}
	}

	if !seenPreauth {
		return nil, &InvalidResponseError{"missing preauth integrity capabilities context"}
	}

	return conn, nil
}

type outstandingRequest struct {
	msgId        uint64
	asyncId      atomic.Uint64
	cmd          smb2.Command
	ctx          context.Context
	recv         chan *recvPacket
	err          error
	canceled     atomic.Bool
	creditCharge uint16

	// readBuf is the caller-provided buffer that the payload of a direct
	// I/O READ response is received into. It is registered by
	// makeOutstandingRequest and consumed at most once by the receiver
	// goroutine.
	readBuf []byte
}

type outstandingRequests struct {
	m        sync.Mutex
	requests map[uint64]*outstandingRequest
}

func newOutstandingRequests() *outstandingRequests {
	return &outstandingRequests{
		requests: make(map[uint64]*outstandingRequest),
	}
}

func (r *outstandingRequests) pop(msgId uint64) (*outstandingRequest, bool) {
	r.m.Lock()
	defer r.m.Unlock()

	rr, ok := r.requests[msgId]
	if !ok {
		return nil, false
	}

	delete(r.requests, msgId)

	return rr, true
}

func (r *outstandingRequests) peek(msgId uint64) (*outstandingRequest, bool) {
	r.m.Lock()
	defer r.m.Unlock()

	rr, ok := r.requests[msgId]
	return rr, ok
}

func (r *outstandingRequests) set(msgId uint64, rr *outstandingRequest) {
	r.m.Lock()
	defer r.m.Unlock()

	r.requests[msgId] = rr
}

func (r *outstandingRequests) shutdown(err error) {
	r.m.Lock()
	defer r.m.Unlock()

	for _, rr := range r.requests {
		rr.err = err
		close(rr.recv)
	}
}

type conn struct {
	t transport

	session                   *session
	outstandingRequests       *outstandingRequests
	dialect                   uint16
	maxTransactSize           uint32
	maxReadSize               uint32
	maxWriteSize              uint32
	writeTimeout              time.Duration
	requireSigning            bool
	capabilities              uint32
	preauthIntegrityHashId    uint16
	preauthIntegrityHashValue [64]byte
	cipherId                  uint16

	account *account

	rdone chan struct{}

	m sync.Mutex

	err error

	// gssNegotiateToken []byte
	// serverGuid        [16]byte
	// clientGuid        [16]byte

	_useSession int32 // receiver use session?

	// reusable encode/encryption buffer. use it with sync.Mutex

	encodeBuf  []byte
	encryptBuf []byte
}

const minBufSize = 1024

func (conn *conn) allocEncodeBuf(size int) []byte {
	return conn.allocBuf(&conn.encodeBuf, size)
}

func (conn *conn) allocEncryptBuf(size int) []byte {
	return conn.allocBuf(&conn.encryptBuf, size)
}

func (conn *conn) allocBuf(buf *[]byte, size int) []byte {
	if cap(*buf) < size {
		newCap := size
		if newCap < minBufSize {
			newCap = minBufSize
		}
		*buf = make([]byte, newCap)
	} else {
		clear((*buf)[:size])
	}
	*buf = (*buf)[:size]
	return *buf
}

func updatePreauthHash(hashVal *[64]byte, pkt []byte) {
	h := sha512.New()
	h.Write(hashVal[:])
	h.Write(pkt)
	h.Sum(hashVal[:0])
}

func (conn *conn) useSession() bool {
	return atomic.LoadInt32(&conn._useSession) != 0
}

func (conn *conn) enableSession() {
	atomic.StoreInt32(&conn._useSession, 1)
}

func (conn *conn) maxCreditSize() int {
	maxSize := singleCreditMaxPayloadSize
	if conn.account != nil {
		if creditCap := int64(conn.account.maxCreditCap()) * singleCreditMaxPayloadSize; creditCap > 0 {
			maxSize = int(min(creditCap, int64(winMaxPayloadSize)))
		}
	}
	return maxSize
}

func (conn *conn) closeLocked(err error) error {
	if conn.err != nil {
		return nil
	}
	if err == nil {
		err = &TransportError{Err: net.ErrClosed}
	}
	conn.err = err

	if conn.account != nil {
		conn.account.abort(err)
	}

	select {
	case conn.rdone <- struct{}{}:
	default:
	}

	return conn.t.Close()
}

func (conn *conn) close(err error) error {
	conn.m.Lock()
	defer conn.m.Unlock()

	return conn.closeLocked(err)
}

func (conn *conn) sendRecv(ctx context.Context, reqs ...smb2.Packet) (*response, error) {
	rrs, err := conn.send(ctx, false, reqs...)
	if err != nil {
		return nil, err
	}
	return recvAll(rrs, conn)
}

/*
mustSign returns true if req needs to be signed.

MS-SMB2 3.2.4.1.1 describes when a message needs to be signed.
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/973630a8-8aa1-4398-89a8-13cf830f194d
*/
func (conn *conn) mustSign(sessionFlags uint16, req smb2.Packet) bool {
	if _, isSessionSetup := req.(*smb2.SessionSetupRequest); isSessionSetup {
		return false
	}

	// a 'guest' user or a session without a key can't sign requests
	if sessionFlags&(smb2.SMB2_SESSION_FLAG_IS_GUEST|smb2.SMB2_SESSION_FLAG_IS_NULL) != 0 {
		return false
	}

	// true if the library user requested it at initialization or if the server
	// requires it
	if conn.requireSigning {
		return true
	}

	// Only SMB 3.1.1 requires TREE_CONNECT to always be signed, but for
	// simplicity's sake, we'll sign it no matter the dialect version.
	_, isTreeConnect := req.(*smb2.TreeConnectRequest)
	return isTreeConnect
}

func (conn *conn) send(ctx context.Context, encrypt bool, reqs ...smb2.Packet) (rrs []*outstandingRequest, err error) {
	msgIds, totalCreditCharge, err := conn.account.loan(ctx, reqs...)
	if err != nil {
		return nil, err
	}

	conn.m.Lock()
	defer conn.m.Unlock()

	if conn.err != nil {
		conn.account.unloan(totalCreditCharge)
		return nil, conn.err
	}

	select {
	case <-ctx.Done():
		conn.account.unloan(totalCreditCharge)
		return nil, &ContextError{Err: ctx.Err()}
	default:
		// do nothing
	}

	rrs, pkt, err := conn.makeOutstandingRequest(ctx, encrypt, msgIds, reqs...)
	if err != nil {
		conn.account.unloan(totalCreditCharge)
		return nil, err
	}

	err = conn.sendRaw(ctx, pkt)
	if err != nil {
		for _, rr := range rrs {
			conn.outstandingRequests.pop(rr.msgId)
		}
		conn.account.unloan(totalCreditCharge)
		terr := &TransportError{err}
		// the transport is broken, tear down the connection
		conn.closeLocked(terr)
		return nil, terr
	}

	return rrs, nil
}

func (conn *conn) sendRaw(ctx context.Context, pkt []byte) error {
	timeout := conn.writeTimeout
	if timeout <= 0 {
		timeout = defaultWriteTimeout
	}
	deadline := time.Now().Add(timeout)
	if ctxDeadline, ok := ctx.Deadline(); ok && ctxDeadline.Before(deadline) {
		deadline = ctxDeadline
	}
	if err := conn.t.SetWriteDeadline(deadline); err != nil {
		return err
	}
	defer conn.t.SetWriteDeadline(time.Time{})

	_, err := conn.t.Write(pkt)
	return err
}

func (conn *conn) makeOutstandingRequest(ctx context.Context, encrypt bool, msgIds []uint64, reqs ...smb2.Packet) (rrs []*outstandingRequest, pkt []byte, err error) {
	s := conn.session
	rrs = make([]*outstandingRequest, len(reqs))

	// Compound request (len(reqs) > 1)
	var totalSize int
	sizes := make([]int, len(reqs))
	for i, req := range reqs {
		sz := req.Size()
		if i < len(reqs)-1 {
			alignedSz := smb2.Roundup(sz, 8)
			req.SetNextCommand(uint32(alignedSz))
			sizes[i] = alignedSz
			totalSize += alignedSz
		} else {
			req.SetNextCommand(0)
			sizes[i] = sz
			totalSize += sz
		}
	}

	for i, req := range reqs {
		msgId := msgIds[i]

		if i > 0 {
			req.SetFlags(smb2.SMB2_FLAGS_RELATED_OPERATIONS)
		}

		rr := &outstandingRequest{
			cmd:          req.Command(),
			msgId:        msgId,
			ctx:          ctx,
			recv:         make(chan *recvPacket, 1),
			creditCharge: req.CreditCharge(),
		}

		if drr, ok := req.(*directReadRequest); ok {
			rr.readBuf = drr.b
		}

		rrs[i] = rr
	}

	pkt = conn.allocEncodeBuf(totalSize)

	off := 0
	for i, req := range reqs {
		req.Encode(pkt[off:])
		off += sizes[i]
	}

	if s != nil && encrypt {
		encSize := 52 + len(pkt) + 16
		encryptBuf := conn.allocEncryptBuf(encSize)
		pkt, err = s.encrypt(pkt, encryptBuf)
		if err != nil {
			return nil, nil, &InternalError{err.Error()}
		}
	} else if s != nil {
		off = 0
		requireSigning := false
		for _, req := range reqs {
			if conn.mustSign(s.sessionFlags, req) {
				requireSigning = true
				break
			}
		}
		for i := range reqs {
			subPkt := pkt[off : off+sizes[i]]
			if requireSigning {
				s.sign(subPkt)
			}
			off += sizes[i]
		}
	}

	for _, rr := range rrs {
		conn.outstandingRequests.set(rr.msgId, rr)
	}

	return rrs, pkt, nil
}

func (conn *conn) recv(rr *outstandingRequest) (*recvPacket, error) {
	acceptResponse := func(rp *recvPacket) (*recvPacket, error) {
		if rp == nil {
			// the channel was closed by conn.close while rr was outstanding
			if rr.err != nil {
				return nil, rr.err
			}
			return nil, &TransportError{Err: net.ErrClosed}
		}
		if rr.err != nil {
			rp.close()
			return nil, rr.err
		}
		return accept(rr.cmd, rp)
	}

	// A response may have already arrived while the context was being
	// canceled: prefer the buffered response over the cancellation.
	select {
	case rp := <-rr.recv:
		return acceptResponse(rp)
	default:
	}

	select {
	case rp := <-rr.recv:
		return acceptResponse(rp)
	case <-rr.ctx.Done():
		rr.canceled.Store(true)

		go conn.sendCancel(rr)

		select {
		case rp := <-rr.recv:
			if rp != nil {
				rp.close()
			}
		default:
		}

		return nil, &ContextError{Err: rr.ctx.Err()}
	}
}

func (conn *conn) sendCancel(rr *outstandingRequest) {
	req := &smb2.CancelRequest{}
	req.SetMessageId(rr.msgId)
	if asyncId := rr.asyncId.Load(); asyncId != 0 {
		req.SetFlags(smb2.SMB2_FLAGS_ASYNC_COMMAND)
		req.AsyncId = asyncId
	}

	conn.m.Lock()
	defer conn.m.Unlock()
	if conn.err != nil {
		return
	}

	if s := conn.session; s != nil {
		req.SetSessionId(s.sessionId)
	}

	pkt := conn.allocEncodeBuf(req.Size())
	req.Encode(pkt)

	if s := conn.session; s != nil {
		if conn.requireSigning || s.sessionFlags&(smb2.SMB2_SESSION_FLAG_IS_GUEST|smb2.SMB2_SESSION_FLAG_IS_NULL) == 0 {
			s.sign(pkt)
		}
	}

	if err := conn.sendRaw(context.Background(), pkt); err != nil {
		conn.closeLocked(&TransportError{err})
	}
}

func (conn *conn) runReceiver() {
	var err error

	// A panic should shutdown the connection
	defer func() {
		if r := recover(); r != nil {
			err = &InvalidResponseError{fmt.Sprintf("receiver panic: %v", r)}
			conn.m.Lock()
			defer conn.m.Unlock()
			conn.outstandingRequests.shutdown(err)
			conn.err = err
			if conn.account != nil {
				conn.account.abort(err)
			}
			if conn.t != nil {
				_ = conn.t.Close()
			}
		}
	}()

	for {
		rp, e := conn.t.ReadPacket(conn.directReadSink)
		if e != nil {
			err = &TransportError{e}

			goto exit
		}

		hasSession := conn.useSession()

		var isEncrypted bool

		if hasSession {
			var errDecrypt error
			rp, isEncrypted, errDecrypt = conn.tryDecrypt(rp)
			if errDecrypt != nil {
				rp.close()
				err = errDecrypt
				goto exit
			}

			p := rp.codec()
			if s := conn.session; s != nil {
				if s.sessionId != p.SessionId() {
					rp.close()
					err = &InvalidResponseError{"unknown session id"}
					goto exit
				}
			}
		}

		p := rp.codec()

		// validate the packet if it doesn't have a session yet. tryDecrypt
		// already checks the packet validity when there is a session.
		if !hasSession && p.IsInvalid() {
			rp.close()
			err = &InvalidResponseError{"invalid packet header"}
			goto exit
		}

		for {
			// split must be called before tryHandle because tryHandle may
			// close rp.
			next := p.NextCommand()

			var sub *recvPacket
			if next != 0 {
				sub = rp.split(next)
				if sp := sub.codec(); sp.IsInvalid() {
					rp.close()
					sub.close()
					err = &InvalidResponseError{"invalid chained packet header"}
					goto exit
				}
			}

			if hasSession {
				e = conn.tryVerify(rp, isEncrypted)
			}

			if e := conn.tryHandle(rp, e); e != nil {
				logger.Println("skip:", e)
			}

			if sub == nil {
				break
			}

			rp = sub
			p = rp.codec()
		}
	}

exit:
	select {
	case <-conn.rdone:
		err = nil
	default:
		logger.Println("error:", err)
	}

	conn.m.Lock()
	defer conn.m.Unlock()

	if conn.err != nil {
		err = conn.err
	}

	if conn.account != nil {
		conn.account.abort(err)
	}

	conn.outstandingRequests.shutdown(err)

	conn.err = err

	if conn.t != nil {
		_ = conn.t.Close()
	}
}

// directReadSink inspects the packet head and returns the caller-provided
// buffer (and front-end header size) for a direct I/O READ response.
func (conn *conn) directReadSink(head []byte, restSize int) ([]byte, int) {
	p := smb2.PacketCodec(head)
	if p.IsInvalid() ||
		p.Command() != smb2.SMB2_READ ||
		p.NextCommand() != 0 ||
		erref.NtStatus(p.Status()) != erref.STATUS_SUCCESS {
		return nil, 0
	}

	r := smb2.ReadResponseDecoder(p.Body())
	if r.IsInvalidHeader() {
		return nil, 0
	}

	rr, ok := conn.outstandingRequests.peek(p.MessageId())
	if !ok || rr.canceled.Load() || len(rr.readBuf) == 0 {
		return nil, 0
	}

	// [MS-SMB2] 2.2.20: the data must exactly fill the rest of the packet
	// and fit in the caller's buffer.
	frontSize := int(r.DataOffset())
	dataLength := int(r.DataLength())
	pad := frontSize - 80
	if pad < 0 || pad+dataLength != restSize || dataLength > len(rr.readBuf) {
		return nil, 0
	}

	return rr.readBuf[:dataLength], frontSize
}

func accept(cmd smb2.Command, rp *recvPacket) (res *recvPacket, err error) {
	defer func() {
		if res == nil {
			rp.close()
		}
	}()

	p := rp.codec()

	if command := p.Command(); cmd != command {
		return nil, &InvalidResponseError{fmt.Sprintf("expected command: %s, got %s", cmd.String(), command.String())}
	}

	status := erref.NtStatus(p.Status())

	switch status {
	case erref.STATUS_SUCCESS:
		// For a direct I/O response, the payload is already in the caller's
		// buffer and was validated during reception (see directReadSink),
		// so the generic data coverage check doesn't apply.
		if rp.ext == nil && cmd.IsInvalid(p.Body()) {
			return nil, &InvalidResponseError{fmt.Sprintf("broken %s response format", cmd.String())}
		}
		return rp, nil

	case erref.STATUS_MORE_PROCESSING_REQUIRED:
		if cmd == smb2.SMB2_SESSION_SETUP {
			return rp, nil
		}

	case erref.STATUS_BUFFER_OVERFLOW:
		switch cmd {
		case smb2.SMB2_QUERY_INFO:
			r := smb2.QueryInfoResponseDecoder(p.Body())
			if !r.IsInvalid() {
				return nil, &ResponseError{Code: uint32(status), data: [][]byte{append([]byte(nil), r.OutputBuffer()...)}}
			}
		case smb2.SMB2_IOCTL:
			r := smb2.IoctlResponseDecoder(p.Body())
			if !r.IsInvalid() {
				return nil, &ResponseError{Code: uint32(status), data: [][]byte{append([]byte(nil), r.Output()...)}}
			}
		case smb2.SMB2_READ:
			r := smb2.ReadResponseDecoder(p.Body())
			if !r.IsInvalid() {
				return nil, &ResponseError{Code: uint32(status), data: [][]byte{append([]byte(nil), r.Data()...)}}
			}
		}

	case erref.STATUS_NOTIFY_ENUM_DIR:
		if cmd == smb2.SMB2_CHANGE_NOTIFY {
			return nil, &ResponseError{Code: uint32(status)}
		}
	}

	return nil, acceptError(uint32(status), p.Body())
}

func acceptError(status uint32, res []byte) error {
	r := smb2.ErrorResponseDecoder(res)
	if r.IsInvalid() {
		return &InvalidResponseError{"broken error response format"}
	}

	eData := r.ErrorData()

	if count := r.ErrorContextCount(); count != 0 {
		data := make([][]byte, count)

		for i := range data {
			ctx := smb2.ErrorContextResponseDecoder(eData)
			if ctx.IsInvalid() {
				return &InvalidResponseError{"broken error context response format"}
			}

			data[i] = append([]byte(nil), ctx.ErrorContextData()...)

			// the last error context need not be padded to the 8-byte boundary (MS-SMB2 2.2.2)
			if i == len(data)-1 {
				break
			}

			next := ctx.Next()

			if len(eData) < next {
				return &InvalidResponseError{"broken error context response format"}
			}

			eData = eData[next:]
		}
		return &ResponseError{Code: status, data: data}
	}
	return &ResponseError{Code: status, data: [][]byte{append([]byte(nil), eData...)}}
}

func (conn *conn) tryDecrypt(rp *recvPacket) (*recvPacket, bool, error) {
	p := rp.codec()
	if p.IsInvalid() {
		t := rp.transformCodec()
		if t.IsInvalid() {
			return rp, false, &InvalidResponseError{"broken packet header format"}
		}

		if t.Flags() != smb2.Encrypted {
			return rp, false, &InvalidResponseError{"encrypted flag is not on"}
		}

		if conn.session == nil || conn.session.sessionId != t.SessionId() {
			return rp, false, &InvalidResponseError{"unknown session id returned"}
		}

		pkt, err := conn.session.decrypt(rp.bytes())
		if err != nil {
			return rp, false, &InvalidResponseError{err.Error()}
		}

		if smb2.PacketCodec(pkt).IsInvalid() {
			return rp, false, &InvalidResponseError{"broken decrypted packet format"}
		}

		rp.pkt = pkt
		return rp, true, nil
	}

	return rp, false, nil
}

func (conn *conn) tryVerify(rp *recvPacket, isEncrypted bool) error {
	p := rp.codec()

	msgID := p.MessageId()

	// MS-SMB2 3.2.5.1.3 states that the client MUST skip signature processing if:
	// - MessageId is 0xFFFFFFFFFFFFFFFF
	// - Status in the SMB2 header is STATUS_PENDING
	// 		- 3.3.4.1.1 says servers should skip signing interim responses to async requests - STATUS_PENDING is an interim response
	// - Client is using the SMB 3.x dialect and the message was successfully decrypted+authenticated (isEncrypted=true)
	if msgID == 0xFFFFFFFFFFFFFFFF {
		return nil
	}
	if erref.NtStatus(p.Status()) == erref.STATUS_PENDING {
		return nil
	}
	if isEncrypted {
		return nil
	}

	s := conn.session
	if s == nil {
		return &InvalidResponseError{"packet received before session established"}
	}
	if s.sessionId != p.SessionId() {
		return &InvalidResponseError{"packet for unknown session"}
	}

	// guest and null sessions can't produce signatures, so they don't need to be verified
	if s.sessionFlags&(smb2.SMB2_SESSION_FLAG_IS_GUEST|smb2.SMB2_SESSION_FLAG_IS_NULL) != 0 {
		return nil
	}

	// verify if 1) the connection requires signing or 2) if the message itself is signed
	if conn.requireSigning || p.Flags()&smb2.SMB2_FLAGS_SIGNED != 0 {
		if !s.verify(rp.pkt, rp.ext) {
			return &InvalidResponseError{"packet failed signature verification"}
		}
		return nil
	}

	// the message was not signed AND signing is not required
	return nil
}

func (conn *conn) tryHandle(rp *recvPacket, e error) error {
	p := rp.codec()

	msgId := p.MessageId()

	rr, ok := conn.outstandingRequests.pop(msgId)
	switch {
	case !ok:
		conn.account.charge(p.CreditResponse(), 0)
		rp.close()
		return &InvalidResponseError{"unknown message id returned"}
	case e != nil:
		conn.account.charge(p.CreditResponse(), rr.creditCharge)
		rp.close()
		rr.err = e

		if !rr.canceled.Load() {
			close(rr.recv)
		}
	case erref.NtStatus(p.Status()) == erref.STATUS_PENDING:
		conn.account.charge(p.CreditResponse(), 0)
		rp.close()
		// Per [MS-SMB2] 3.3.5.2.2, only an async interim response carries an
		// async id; for a synchronous pending response the field actually
		// holds the tree id and must not be adopted.
		if p.Flags()&smb2.SMB2_FLAGS_ASYNC_COMMAND != 0 {
			rr.asyncId.Store(p.AsyncId())
		}
		conn.outstandingRequests.set(msgId, rr)
	default:
		conn.account.charge(p.CreditResponse(), rr.creditCharge)

		if rr.canceled.Load() {
			rp.close()
			return nil
		}

		rr.recv <- rp

		// rr.ctx may have been canceled between the canceled check and the
		// send above. Drain the response back, otherwise nobody will close
		// it and its buffer leaks.
		if rr.canceled.Load() {
			select {
			case rp := <-rr.recv:
				if rp != nil {
					rp.close()
				}
			default:
			}
		}
	}

	return nil
}
