package smb2

import (
	"context"
	"crypto/rand"
	"crypto/sha512"
	"fmt"
	"sync"
	"sync/atomic"
	"time"

	"github.com/hirochachacha/go-smb2/internal/erref"
	"github.com/hirochachacha/go-smb2/internal/smb2"
)

// Negotiator contains options for func (*Dialer) Dial.
type Negotiator struct {
	RequireMessageSigning bool     // enforce signing?
	ClientGuid            [16]byte // if it's zero, generated by crypto/rand.
	SpecifiedDialect      uint16   // if it's zero, clientDialects is used. (See feature.go for more details)
}

func (n *Negotiator) makeRequest() (*smb2.NegotiateRequest, error) {
	req := new(smb2.NegotiateRequest)

	if n.RequireMessageSigning {
		req.SecurityMode = smb2.SMB2_NEGOTIATE_SIGNING_REQUIRED
	} else {
		req.SecurityMode = smb2.SMB2_NEGOTIATE_SIGNING_ENABLED
	}

	req.Capabilities = clientCapabilities

	if n.ClientGuid == zero {
		_, err := rand.Read(req.ClientGuid[:])
		if err != nil {
			return nil, &InternalError{err.Error()}
		}
	} else {
		req.ClientGuid = n.ClientGuid
	}

	if n.SpecifiedDialect != smb2.UnknownSMB {
		req.Dialects = []uint16{n.SpecifiedDialect}

		switch n.SpecifiedDialect {
		case smb2.SMB202:
		case smb2.SMB210:
		case smb2.SMB300:
		case smb2.SMB302:
		case smb2.SMB311:
			hc := &smb2.HashContext{
				HashAlgorithms: clientHashAlgorithms,
				HashSalt:       make([]byte, 32),
			}
			if _, err := rand.Read(hc.HashSalt); err != nil {
				return nil, &InternalError{err.Error()}
			}

			cc := &smb2.CipherContext{
				Ciphers: clientCiphers,
			}

			req.Contexts = append(req.Contexts, hc, cc)
		default:
			return nil, &InternalError{"unsupported dialect specified"}
		}
	} else {
		req.Dialects = clientDialects

		hc := &smb2.HashContext{
			HashAlgorithms: clientHashAlgorithms,
			HashSalt:       make([]byte, 32),
		}
		if _, err := rand.Read(hc.HashSalt); err != nil {
			return nil, &InternalError{err.Error()}
		}

		cc := &smb2.CipherContext{
			Ciphers: clientCiphers,
		}

		req.Contexts = append(req.Contexts, hc, cc)
	}

	return req, nil
}

func (n *Negotiator) negotiate(t transport, a *account, ctx context.Context) (c *conn, err error) {
	conn := &conn{
		t:                   t,
		outstandingRequests: newOutstandingRequests(),
		account:             a,
		rdone:               make(chan struct{}, 1),
	}

	defer func() {
		if err != nil {
			conn.close(err)
		}
	}()

	go conn.runReceiver()

	neg := *n

retry:
	req, err := neg.makeRequest()
	if err != nil {
		return nil, err
	}

	res, err := conn.sendRecv(ctx, req)
	if err != nil {
		return nil, err
	}
	defer res.close()

	r := smb2.NegotiateResponseDecoder(res.data(0))

	if r.DialectRevision() == smb2.SMB2 {
		neg.SpecifiedDialect = smb2.SMB210

		goto retry
	}

	if neg.SpecifiedDialect != smb2.UnknownSMB && neg.SpecifiedDialect != r.DialectRevision() {
		return nil, &InvalidResponseError{"unexpected dialect returned"}
	}

	conn.requireSigning = neg.RequireMessageSigning || r.SecurityMode()&smb2.SMB2_NEGOTIATE_SIGNING_REQUIRED != 0
	conn.capabilities = clientCapabilities & r.Capabilities()
	conn.dialect = r.DialectRevision()
	conn.maxTransactSize = r.MaxTransactSize()
	conn.maxReadSize = r.MaxReadSize()
	conn.maxWriteSize = r.MaxWriteSize()

	// conn.gssNegotiateToken = r.SecurityBuffer()
	// conn.clientGuid = n.ClientGuid
	// copy(conn.serverGuid[:], r.ServerGuid())

	if conn.dialect != smb2.SMB311 {
		return conn, nil
	}

	// handle context for SMB311
	list := r.NegotiateContextList()
	for count := r.NegotiateContextCount(); count > 0; count-- {
		ctx := smb2.NegotiateContextDecoder(list)
		if ctx.IsInvalid() {
			return nil, &InvalidResponseError{"broken negotiate context format"}
		}

		switch ctx.ContextType() {
		case smb2.SMB2_PREAUTH_INTEGRITY_CAPABILITIES:
			d := smb2.HashContextDataDecoder(ctx.Data())
			if d.IsInvalid() {
				return nil, &InvalidResponseError{"broken hash context data format"}
			}

			algs := d.HashAlgorithms()

			if len(algs) != 1 {
				return nil, &InvalidResponseError{"multiple hash algorithms"}
			}

			conn.preauthIntegrityHashId = algs[0]

			switch conn.preauthIntegrityHashId {
			case smb2.SHA512:
				// Handshake requests are executed sequentially without concurrent access,
				// so conn.encodeBuf still holds the encoded request packet.
				updatePreauthHash(&conn.preauthIntegrityHashValue, conn.encodeBuf)
				updatePreauthHash(&conn.preauthIntegrityHashValue, res.bytes(0))
			default:
				return nil, &InvalidResponseError{"unknown hash algorithm"}
			}
		case smb2.SMB2_ENCRYPTION_CAPABILITIES:
			d := smb2.CipherContextDataDecoder(ctx.Data())
			if d.IsInvalid() {
				return nil, &InvalidResponseError{"broken cipher context data format"}
			}

			ciphs := d.Ciphers()

			if len(ciphs) != 1 {
				return nil, &InvalidResponseError{"multiple cipher algorithms"}
			}

			conn.cipherId = ciphs[0]

			switch conn.cipherId {
			case smb2.AES128CCM:
			case smb2.AES128GCM:
			default:
				return nil, &InvalidResponseError{"unknown cipher algorithm"}
			}
		default:
			// skip unsupported context
		}

		off := ctx.Next()

		if len(list) < off {
			list = nil
		} else {
			list = list[off:]
		}
	}

	return conn, nil
}

type outstandingRequest struct {
	msgId   uint64
	asyncId uint64
	cmd     smb2.Command
	ctx     context.Context
	recv    chan *recvPacket
	err     error
}

type outstandingRequests struct {
	m        sync.Mutex
	requests map[uint64]*outstandingRequest
}

func newOutstandingRequests() *outstandingRequests {
	return &outstandingRequests{
		requests: make(map[uint64]*outstandingRequest),
	}
}

func (r *outstandingRequests) pop(msgId uint64) (*outstandingRequest, bool) {
	r.m.Lock()
	defer r.m.Unlock()

	rr, ok := r.requests[msgId]
	if !ok {
		return nil, false
	}

	delete(r.requests, msgId)

	return rr, true
}

func (r *outstandingRequests) set(msgId uint64, rr *outstandingRequest) {
	r.m.Lock()
	defer r.m.Unlock()

	r.requests[msgId] = rr
}

func (r *outstandingRequests) shutdown(err error) {
	r.m.Lock()
	defer r.m.Unlock()

	for _, rr := range r.requests {
		rr.err = err
		close(rr.recv)
	}
}

type conn struct {
	t transport

	session                   *session
	outstandingRequests       *outstandingRequests
	sequenceWindow            uint64
	dialect                   uint16
	maxTransactSize           uint32
	maxReadSize               uint32
	maxWriteSize              uint32
	requireSigning            bool
	capabilities              uint32
	preauthIntegrityHashId    uint16
	preauthIntegrityHashValue [64]byte
	cipherId                  uint16

	account *account

	rdone chan struct{}

	m sync.Mutex

	err error

	// gssNegotiateToken []byte
	// serverGuid        [16]byte
	// clientGuid        [16]byte

	_useSession int32 // receiver use session?

	// reusable encode/encryption buffer. use it with sync.Mutex

	encodeBuf  []byte
	encryptBuf []byte
}

const minBufSize = 1024

func (conn *conn) allocEncodeBuf(size int) []byte {
	return conn.allocBuf(&conn.encodeBuf, size)
}

func (conn *conn) allocEncryptBuf(size int) []byte {
	return conn.allocBuf(&conn.encryptBuf, size)
}

func (conn *conn) allocBuf(buf *[]byte, size int) []byte {
	if cap(*buf) < size {
		newCap := size
		if newCap < minBufSize {
			newCap = minBufSize
		}
		*buf = make([]byte, newCap)
	} else {
		clear((*buf)[:size])
	}
	return (*buf)[:size]
}

func updatePreauthHash(hashVal *[64]byte, pkt []byte) {
	h := sha512.New()
	h.Write(hashVal[:])
	h.Write(pkt)
	h.Sum(hashVal[:0])
}

func (conn *conn) useSession() bool {
	return atomic.LoadInt32(&conn._useSession) != 0
}

func (conn *conn) enableSession() {
	atomic.StoreInt32(&conn._useSession, 1)
}

func (conn *conn) newTimer() *time.Timer {
	return time.NewTimer(5 * time.Second)
}

func (conn *conn) maxCreditSize() int {
	rc := singleCreditMaxPayloadSize
	if conn.account != nil {
		if cap := int(conn.account.maxCreditCap()) * singleCreditMaxPayloadSize; cap > 0 {
			rc = cap
		}
	}
	return rc
}

func (conn *conn) close(err error) error {
	conn.m.Lock()
	if conn.err != nil {
		conn.m.Unlock()
		return nil
	}
	conn.err = err
	conn.m.Unlock()

	select {
	case conn.rdone <- struct{}{}:
	default:
	}

	return conn.t.Close()
}

func (conn *conn) sendRecv(ctx context.Context, reqs ...smb2.Packet) (*response, error) {
	rrs, err := conn.send(ctx, false, reqs...)
	if err != nil {
		return nil, err
	}
	return recvAll(rrs, conn)
}

/*
mustSign returns true if req needs to be signed.

MS-SMB2 3.2.4.1.1 describes when a message needs to be signed.
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/973630a8-8aa1-4398-89a8-13cf830f194d
*/
func (conn *conn) mustSign(sessionFlags uint16, req smb2.Packet) bool {
	if _, isSessionSetup := req.(*smb2.SessionSetupRequest); isSessionSetup {
		return false
	}

	// a 'guest' user or a session without a key can't sign requests
	if sessionFlags&(smb2.SMB2_SESSION_FLAG_IS_GUEST|smb2.SMB2_SESSION_FLAG_IS_NULL) != 0 {
		return false
	}

	// true if the library user requested it at initialization or if the server
	// requires it
	if conn.requireSigning {
		return true
	}

	// Only SMB 3.1.1 requires TREE_CONNECT to always be signed, but for
	// simplicity's sake, we'll sign it no matter the dialect version.
	_, isTreeConnect := req.(*smb2.TreeConnectRequest)
	return isTreeConnect
}

func (conn *conn) send(ctx context.Context, encrypt bool, reqs ...smb2.Packet) (rrs []*outstandingRequest, err error) {
	msgIds, totalCreditCharge, err := conn.account.loan(ctx, reqs...)
	if err != nil {
		return nil, err
	}

	conn.m.Lock()
	defer conn.m.Unlock()

	if conn.err != nil {
		conn.account.unloan(totalCreditCharge)
		return nil, conn.err
	}

	select {
	case <-ctx.Done():
		conn.account.unloan(totalCreditCharge)
		return nil, &ContextError{Err: ctx.Err()}
	default:
		// do nothing
	}

	rrs, pkt, err := conn.makeOutstandingRequest(ctx, encrypt, msgIds, reqs...)
	if err != nil {
		conn.account.unloan(totalCreditCharge)
		return nil, err
	}

	_, err = conn.t.Write(pkt)
	if err != nil {
		for _, rr := range rrs {
			conn.outstandingRequests.pop(rr.msgId)
		}
		conn.account.unloan(totalCreditCharge)
		return nil, &TransportError{err}
	}

	return rrs, nil
}

func (conn *conn) makeOutstandingRequest(ctx context.Context, encrypt bool, msgIds []uint64, reqs ...smb2.Packet) (rrs []*outstandingRequest, pkt []byte, err error) {
	s := conn.session
	rrs = make([]*outstandingRequest, len(reqs))

	// Compound request (len(reqs) > 1)
	var totalSize int
	sizes := make([]int, len(reqs))
	for i, req := range reqs {
		sz := req.Size()
		if i < len(reqs)-1 {
			alignedSz := smb2.Roundup(sz, 8)
			req.SetNextCommand(uint32(alignedSz))
			sizes[i] = alignedSz
			totalSize += alignedSz
		} else {
			req.SetNextCommand(0)
			sizes[i] = sz
			totalSize += sz
		}
	}

	for i, req := range reqs {
		msgId := msgIds[i]

		if i > 0 {
			req.SetFlags(smb2.SMB2_FLAGS_RELATED_OPERATIONS)
		}

		rr := &outstandingRequest{
			cmd:   req.Command(),
			msgId: msgId,
			ctx:   ctx,
			recv:  make(chan *recvPacket, 1),
		}

		rrs[i] = rr
	}

	pkt = conn.allocEncodeBuf(totalSize)

	off := 0
	for i, req := range reqs {
		req.Encode(pkt[off:])
		off += sizes[i]
	}

	if s != nil && encrypt {
		encSize := 52 + len(pkt) + 16
		encryptBuf := conn.allocEncryptBuf(encSize)
		pkt, err = s.encrypt(pkt, encryptBuf)
		if err != nil {
			return nil, nil, &InternalError{err.Error()}
		}
	} else if s != nil {
		off = 0
		requireSigning := false
		for _, req := range reqs {
			if conn.mustSign(s.sessionFlags, req) {
				requireSigning = true
				break
			}
		}
		for i := range reqs {
			subPkt := pkt[off : off+sizes[i]]
			if requireSigning {
				s.sign(subPkt)
			}
			off += sizes[i]
		}
	}

	for _, rr := range rrs {
		conn.outstandingRequests.set(rr.msgId, rr)
	}

	return rrs, pkt, nil
}

func (conn *conn) recv(rr *outstandingRequest) (*recvPacket, error) {
	select {
	case rp := <-rr.recv:
		if rr.err != nil {
			return nil, rr.err
		}
		rp, err := accept(rr.cmd, rp)
		if err != nil {
			return nil, err
		}
		return rp, nil
	case <-rr.ctx.Done():
		conn.outstandingRequests.pop(rr.msgId)

		return nil, &ContextError{Err: rr.ctx.Err()}
	}
}

func (conn *conn) runReceiver() {
	var err error

	// A panic should shutdown the connection
	defer func() {
		if r := recover(); r != nil {
			err = &InvalidResponseError{fmt.Sprintf("receiver panic: %v", r)}
			conn.m.Lock()
			defer conn.m.Unlock()
			conn.outstandingRequests.shutdown(err)
			conn.err = err
		}
	}()

	for {
		n, e := conn.t.ReadSize()
		if e != nil {
			err = &TransportError{e}

			goto exit
		}

		rp := allocRecvPacket(n)

		_, e = conn.t.Read(rp.bytes())
		if e != nil {
			rp.close()
			err = &TransportError{e}

			goto exit
		}

		hasSession := conn.useSession()

		var isEncrypted bool

		if hasSession {
			var errDecrypt error
			rp, errDecrypt, isEncrypted = conn.tryDecrypt(rp)
			if errDecrypt != nil {
				rp.close()
				logger.Println("skip:", errDecrypt)

				continue
			}

			p := rp.codec()
			if s := conn.session; s != nil {
				if s.sessionId != p.SessionId() {
					rp.close()
					logger.Println("skip:", &InvalidResponseError{"unknown session id"})

					continue
				}
			}
		}

		p := rp.codec()

		// validate the packet if it doesn't have a session yet. tryDecrypt
		// already checks the packet validity when there is a session.
		if !hasSession && p.IsInvalid() {
			rp.close()
			logger.Println("skip:", &InvalidResponseError{"invalid packet header"})
			continue
		}

		for {
			// split must be called before tryHandle because tryHandle may
			// close rp.
			next := p.NextCommand()

			var sub *recvPacket
			if next != 0 {
				if next < 64 || uint64(next) > uint64(len(rp.pkt)) {
					logger.Println("skip:", &InvalidResponseError{"NextCommand offset out of bounds"})
				} else {
					sub = rp.split(next)
					if sp := sub.codec(); sp.IsInvalid() {
						logger.Println("skip:", &InvalidResponseError{"invalid chained packet header"})
						sub.close()
						sub = nil
					}
				}
			}

			if hasSession {
				e = conn.tryVerify(rp.bytes(), isEncrypted)
			}

			if e := conn.tryHandle(rp, e); e != nil {
				logger.Println("skip:", e)
			}

			if sub == nil {
				break
			}

			rp = sub
			p = rp.codec()
		}
	}

exit:
	select {
	case <-conn.rdone:
		err = nil
	default:
		logger.Println("error:", err)
	}

	conn.m.Lock()
	defer conn.m.Unlock()

	if conn.err != nil {
		err = conn.err
	}

	conn.outstandingRequests.shutdown(err)

	conn.err = err
}

func accept(cmd smb2.Command, rp *recvPacket) (res *recvPacket, err error) {
	p := rp.codec()
	if command := p.Command(); cmd != command {
		rp.close()
		return nil, &InvalidResponseError{fmt.Sprintf("expected command: %s, got %s", cmd.String(), command.String())}
	}

	status := erref.NtStatus(p.Status())

	if status == erref.STATUS_SUCCESS {
		if cmd.IsInvalid(p.Data()) {
			rp.close()
			return nil, &InvalidResponseError{fmt.Sprintf("broken %s response format", cmd.String())}
		}
		return rp, nil
	}

	switch cmd {
	case smb2.SMB2_SESSION_SETUP:
		if status == erref.STATUS_MORE_PROCESSING_REQUIRED {
			return rp, nil
		}
	case smb2.SMB2_QUERY_INFO:
		if status == erref.STATUS_BUFFER_OVERFLOW {
			rp.close()
			return nil, &ResponseError{Code: uint32(status)}
		}
	case smb2.SMB2_IOCTL:
		if status == erref.STATUS_BUFFER_OVERFLOW {
			if !smb2.IoctlResponseDecoder(p.Data()).IsInvalid() {
				return rp, &ResponseError{Code: uint32(status)}
			}
		}
	case smb2.SMB2_READ:
		if status == erref.STATUS_BUFFER_OVERFLOW {
			rp.close()
			return nil, &ResponseError{Code: uint32(status)}
		}
	case smb2.SMB2_CHANGE_NOTIFY:
		if status == erref.STATUS_NOTIFY_ENUM_DIR {
			rp.close()
			return nil, &ResponseError{Code: uint32(status)}
		}
	}

	err = acceptError(uint32(status), p.Data())
	rp.close()
	return nil, err
}

func acceptError(status uint32, res []byte) error {
	r := smb2.ErrorResponseDecoder(res)
	if r.IsInvalid() {
		return &InvalidResponseError{"broken error response format"}
	}

	eData := r.ErrorData()

	if count := r.ErrorContextCount(); count != 0 {
		data := make([][]byte, count)

		for i := range data {
			ctx := smb2.ErrorContextResponseDecoder(eData)
			if ctx.IsInvalid() {
				return &InvalidResponseError{"broken error context response format"}
			}

			data[i] = ctx.ErrorContextData()

			next := ctx.Next()

			if len(eData) < next {
				return &InvalidResponseError{"broken error context response format"}
			}

			eData = eData[next:]
		}
		return &ResponseError{Code: status, data: data}
	}
	return &ResponseError{Code: status, data: [][]byte{eData}}
}

func (conn *conn) tryDecrypt(rp *recvPacket) (*recvPacket, error, bool) {
	p := rp.codec()
	if p.IsInvalid() {
		t := rp.transformCodec()
		if t.IsInvalid() {
			return rp, &InvalidResponseError{"broken packet header format"}, false
		}

		if t.Flags() != smb2.Encrypted {
			return rp, &InvalidResponseError{"encrypted flag is not on"}, false
		}

		if conn.session == nil || conn.session.sessionId != t.SessionId() {
			return rp, &InvalidResponseError{"unknown session id returned"}, false
		}

		pkt, err := conn.session.decrypt(rp.bytes())
		if err != nil {
			return rp, &InvalidResponseError{err.Error()}, false
		}

		rp.pkt = pkt
		return rp, nil, true
	}

	return rp, nil, false
}

func (conn *conn) tryVerify(pkt []byte, isEncrypted bool) error {
	p := smb2.PacketCodec(pkt)

	msgID := p.MessageId()

	// MS-SMB2 3.2.5.1.3 states that the client MUST skip signature processing if:
	// - MessageId is 0xFFFFFFFFFFFFFFFF
	// - Status in the SMB2 header is STATUS_PENDING
	// 		- 3.3.4.1.1 says servers should skip signing interim responses to async requests - STATUS_PENDING is an interim response
	// - Client is using the SMB 3.x dialect and the message was successfully decrypted+authenticated (isEncrypted=true)
	if msgID == 0xFFFFFFFFFFFFFFFF {
		return nil
	}
	if erref.NtStatus(p.Status()) == erref.STATUS_PENDING {
		return nil
	}
	if isEncrypted {
		return nil
	}

	s := conn.session
	if s == nil {
		return &InvalidResponseError{"packet received before session established"}
	}
	if s.sessionId != p.SessionId() {
		return &InvalidResponseError{"packet for unknown session"}
	}

	// guest and null sessions can't produce signatures, so they don't need to be verified
	if s.sessionFlags&(smb2.SMB2_SESSION_FLAG_IS_GUEST|smb2.SMB2_SESSION_FLAG_IS_NULL) != 0 {
		return nil
	}

	// verify if 1) the connection requires signing or 2) if the message itself is signed
	if conn.requireSigning || p.Flags()&smb2.SMB2_FLAGS_SIGNED != 0 {
		if !s.verify(pkt) {
			return &InvalidResponseError{"packet failed signature verification"}
		}
		return nil
	}

	// the message was not signed AND signing is not required
	return nil
}

func (conn *conn) tryHandle(rp *recvPacket, e error) error {
	p := rp.codec()

	msgId := p.MessageId()

	rr, ok := conn.outstandingRequests.pop(msgId)
	switch {
	case !ok:
		rp.close()
		return &InvalidResponseError{"unknown message id returned"}
	case e != nil:
		rp.close()
		rr.err = e

		close(rr.recv)
	case erref.NtStatus(p.Status()) == erref.STATUS_PENDING:
		rp.close()
		rr.asyncId = p.AsyncId()
		conn.account.charge(p.CreditResponse())
		conn.outstandingRequests.set(msgId, rr)
	default:
		conn.account.charge(p.CreditResponse())

		rr.recv <- rp
	}

	return nil
}
