on: [push, pull_request]
jobs:
  test_linux:
    strategy:
      matrix:
        go: ["1.27.x"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v3
    - run: |
        mkdir -p /tmp/tmp1
        mkdir -p /tmp/tmp2
        sudo apt install -y samba
        (echo "Passwd123!"; echo "Passwd123!") | sudo smbpasswd -a -s runner
        sudo cp ./.github/smb.conf /etc/samba/smb.conf
        sudo smbd
    - uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~\AppData\Local\go-build
        key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-${{ matrix.go }}-
    - run: |
        cp ./.github/client_conf.json ./
        go test -v -race ./...
  test_windows:
    strategy:
      matrix:
        go: ["1.27.x"]
    runs-on: windows-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v3
    - run: |
        mkdir C:\tmp1
        mkdir C:\tmp2
        net user runner "Passwd123!" /add
        net share tmp1="C:\tmp1" /GRANT:runner,full
        net share tmp2="C:\tmp2" /GRANT:runner,read
    - uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~\AppData\Local\go-build
        key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-${{ matrix.go }}-
    - run: |
        cp ./.github/client_conf.json ./
        go test -v -race ./...
  test_macos:
    strategy:
      matrix:
        go: ["1.27.x"]
    runs-on: macos-15
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v3
    - run: |
        mkdir -p /tmp/tmp1
        mkdir -p /tmp/tmp2
        sudo dscl . -passwd /Users/runner "Passwd123!"
        sudo launchctl enable system/com.apple.smbd
        sudo sharing -a /tmp/tmp1 -s 111
        sudo sharing -a /tmp/tmp2 -s 111
    - uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~\AppData\Local\go-build
        key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-${{ matrix.go }}-
    - run: |
        cp ./.github/client_conf.json ./
        go test -v -race ./...
